### ISSUE TITLE
Apply-PnPTenantTemplate : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by anthonytudor** [SharePoint/sp-starter-kit#221]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Sorry if this is something obvious, but i believe ive followed all the pre-reqs and guidance before running the Apply-PnPTemplate but it just doesnt seem to want to work.

`Apply-PnPTenantTemplate -Path starterkit.pnp`

#### Observed Behavior

`Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

PS C:\WINDOWS\system32> Get-PnPException

Message          : Object reference not set to an instance of an object.
Stacktrace       :    at SharePointPnP.PowerShell.Commands.Utilities.FileUtilities.IsOpenOfficeFile(Stream stream)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ReadTenantTemplate.LoadProvisioningHiera
                   rchyFromFile(String templatePath, ITemplateProviderExtension[] templateProviderExtensions)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

`
#### Steps to Reproduce

As above, ran the Apply-PnPTenantTemplate -Path starterkit.pnp and got the following error. Also ran the Get-PnPException to get more details. Finally, I tried verifying what version of PnP PS commandlets were installed and only 1 version is showing SharePointPnPPowerShellOnline 3.4.1812.2

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
I have seen this type of error when Apply-PnPTenantTemplate was not ran in the "provisioning" folder. The error is saying that starterkit.pnp cannot be found.

**Comment by bazookadaver** [comment]
I didn't even download the files (was so focused on the other pre-requirements that I forgot) so obviously I wasn't in the right folder to run this. Downloaded and ran from the provisioning folder and it worked like a charm. Thanks!

**Comment by mogalemd** [comment]
I have downloaded the files but still when I try to run this command "Apply-PnPTenantTemplate -Path starterkit.pnp" I get the same error "Apply-PnPTenantTemplate Object reference not set to an instance of an object", I think I am running this command under provisioning folder, could you please send me example of this command?
