### ISSUE TITLE
Apply-PnPTenantTemplate : Column '_StubFile' does not exist. It may have been deleted by another user.

### ISSUE THREAD

**Issue by plakhlani** [SharePoint/sp-starter-kit#227]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
After configuring all pre-requisites, following script throws error:
Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="demo"} 

Get-PnPException:

Message          : Column '_StubFile' does not exist. It may have been deleted by another user.
                   /sites/demoportal/SitePages
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                   clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      at OfficeDevPnP.Core.Pages.ClientSidePage.Save(String pageName)
                      at
                   OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web
                   web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation
                   applyingInformation)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTe
                   mplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation
                   provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.Provision
                   Objects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser,
                   ProvisioningTemplateApplyingInformation applyingInformation)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisio
                   ningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId,
                   ProvisioningTemplateApplyingInformation provisioningInfo)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

#### Observed Behavior
- reproducible from dev branch
- reproducible from master branch

#### Steps to Reproduce
- Download latest master branch or dev branch
- goto provisioning folder
- run Apply-PnPTenantTemplate command

**Comment by bcameron1231** [comment]
Hi, we are working on cleaning up the issues list. I realize this ticket is about 1.5 years old. If this still applies to you, could you please open up a new issue in the issues list? Thanks!
