### ISSUE TITLE
Portal Footer does not show up

### ISSUE THREAD

**Issue by Rxie12** [SharePoint/sp-starter-kit#251]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Deploy the footer solution to a SharePoint site and have the customized footer like PortalFooter

#### Observed Behavior
The Footer was not showing in the SP site. In debugging, I got the following exception:

Exception has occurred: DOMException
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.root-48::-moz-focus-inner{border:0;}'.
    at t.window.spModuleLoader.t.insertRule (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:9048)
    at b (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:4581)
    at w (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:6487)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:221185
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:76819
    at t.window.spModuleLoader.t.render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:229191)
    at t.e.(anonymous function) [as render] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:177:67965)
    at Dn (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:190:56073)
    at Mn (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-08.010/sp-webpart-workbench-assembly_en-us_49de587b5fcf1a6bf34e5680fca44c12.js:190:55868)

#### Steps to Reproduce
Create a new solution for Application Customizer, copy across the required code for the portal footer, and modified the localizedResource value for the **MyLinksStrings** in config.json file ([MyLinks in Portal Footer #122](https://github.com/SharePoint/sp-starter-kit/issues/122)).

**Comment by Rxie12** [comment]
I got the run-time exception in both IE and Chrome.

**Comment by Rxie12** [comment]
I ran npm outdated and it showed below.  My VS code shows TypeScript React 3.2.2.

Package                       Current   Wanted   Latest  Location
@types/chai                 3.4.34   3.4.34    4.1.7  solution
@types/es6-promise    0.0.33   0.0.33    3.3.0  solution
@types/mocha             2.2.38   2.2.38    5.2.6  solution
@types/webpack-env   1.13.1   1.13.1   1.13.7  solution
ajv                                 5.2.5    5.2.5    6.9.1  solution
gulp                              3.9.1    3.9.1    4.0.0  solution
office-ui-fabric-react    5.135.0  5.135.0  6.143.0  solution
