### ISSUE TITLE
Apply-PnPTenantTemplate : File not found

### ISSUE THREAD

**Issue by mickyc1** [SharePoint/sp-starter-kit#256]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

I keep getting the error Apply-PnPTenantTemplate : File not found when running the command `Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SitePrefixUrl"="test"}`
I have ran this previously on my tenant (demo prefix sites created) and it has worked but now when I run it again I keep getting this error. I have recloned the repository to make sure that I am started from a clean slate but still getting this error.

#### Expected or Desired Behavior

Template applied to tenant with 3 new sites created with test prefix

#### Observed Behavior

Process errors out with above error, stack trace below:

```
Message          : File Not Found.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                   clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.RegisterA
                   sHubSite(Tenant tenant, String siteUrl, String logoUrl)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.Provision
                   Objects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser,
                   ProvisioningTemplateApplyingInformation applyingInformation)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisio
                   ningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId,
                   ProvisioningTemplateApplyingInformation provisioningInfo)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

```
Any help would be greatly appreciated

**Comment by Kosadchiy** [comment]
I have same issue. Try to change sites prefix, it was helpful for me. For example, try Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SitePrefixUrl"="**contoso**"}

**Comment by bcameron1231** [comment]
Hi, I am unable to reproduce this with the latest code base. I noticed this ticket is over a year old. We are actively working on cleaning up the issues list and this item may have already been address in a previous update. If this is still an issue for you, could you please re-create a new issue in the issues list, so we can better track it.
